### ISSUE TITLE
Bad Idea to have assertThat method  name

### ISSUE THREAD

**Issue by hexwit** [revinate/assertj-json#6]
Currently I am using AssertJ library for http response assertion, and also needed to assert json in the same tests. 
Currently I need to specify namespace for assertThat method, because there is a conflict in names. 
```
com.revinate.assertj.json.JsonPathAssert.assertThat;
```
and
```
org.assertj.core.api.assertThat;
```

Not sure what did you do this, but because of this it is completely inconvenient to write tests using both libraries. 
Why not assertThatJson().method?

Is it possible to provide fix for this situation?

**Comment by jrglee** [comment]
One of the strongest ideas of most of modern assertion libraries, AssertJ included, is the effort to make assertion easy, declarative and transparent regardless of the type of the value being checked. AssertJ achieves that by providing an `assertThat()` that can provide different assertion method based on the input type. The library was built in a way that you only need to do `assertThat(list).isNotEmpty()` instead of `assertThatList(list).isNotEmpty()`. The idea in AssertJ is to use overloads to determine which assertion strategy to use. 

assertj-json is only a small extension that adds an overload to accept a `DocumentContext`. If you import `assertThat` from AssertJ or from this library, it won't cause any collision because the compiler will determine which method to call based on the type. You can only have a conflict if you have two static methods like `assertThat(DocumentContext context)` in your import block. AssertJ core does not implement any assertion that depends on `DocumentContext` because this is an external library.

Here is how AssertJ custom assertions work http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html

One way to consolidate your assertions is to write your own assertion class like. And add the overload that enables assertj-json

```java
import org.assertj.core.api.Assertions;

public class MyProjectAssertions extends Assertions {
        public static JsonPathAssert assertThat(DocumentContext documentContext) {
        return new JsonPathAssert(documentContext);
    }
}
```

In this way you get all the AssertJ core assertions + extension libraries like assertj-json + your own custom project assertions in one single place.

Let me know if you have further questions.

**Comment by hexwit** [comment]
Custom assertion class did the trick, thank you.
